### ISSUE TITLE
13-9-2021 version version of frank-runner tries to download webapp 7.7 instead of snapshot version

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/frank-runner#24]
`Can't get https://nexus.frankframework.org/repository/public/org/ibissource/ibis-adapterframework-webapp/7.7/ibis-adapterframework-webapp-7.7.war to d:\git\frank-runner\download\ibis-adapterframework-webapp-7.7.war`

I guess the metadata.xml is not parsed in the right way or is changed?

### workaround
by adding the `-Dff.version=7.7-20210907.100208` to the startup

it downloads from
`https://nexus.frankframework.org/repository/public/org/ibissource/ibis-adapterframework-webapp/7.7-20210907.100208/ibis-adapterframework-webapp-7.7-20210907.100208.war`

**Comment by jacodg** [comment]
I've tested it by adding -Dff.version=7.7-20210907.100208 to the restart.bat of Frank2Example1 in the examples folder of the Frank!Runner and that is working as expected:

Getting: https://nexus.frankframework.org/repository/public/org/ibissource/ibis-adapterframework-webapp/7.7-20210907.100208/ibis-adapterframework-webapp-7.7-20210907.100208.war
To: C:\Users\M00F069\C\Software\Data\Git\frank-runner\download\ibis-adapterframework-webapp-7.7-20210907.100208.war

And in the Frank!Console I see:

FF! 7.7-20210907.100208: Frank2Example1

Can you give more details on what you are doing and how I can reproduce the problem?

P.s. no changes have been made to the Frank!Runner since the 3th of August

**Comment by jjansenvr** [comment]
If you do not specify the version it tries to download 7.7 otherwise it works fine

Groet

Jeroen
